/**
 * Export Utilities
 * 
 * Functions for exporting data to CSV and PDF formats.
 */

/**
 * Convert data to CSV format and trigger download
 */
export function exportToCSV<T extends Record<string, unknown>>(
  data: T[],
  filename: string,
  columns?: { key: keyof T; label: string }[]
): void {
  if (data.length === 0) {
    console.warn('No data to export');
    return;
  }

  // Determine columns from data if not provided
  const cols = columns || Object.keys(data[0]).map(key => ({
    key: key as keyof T,
    label: key.toString().replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
  }));

  // Create CSV header
  const header = cols.map(col => `"${col.label}"`).join(',');

  // Create CSV rows
  const rows = data.map(item => 
    cols.map(col => {
      const value = item[col.key];
      // Handle different value types
      if (value === null || value === undefined) {
        return '""';
      }
      if (typeof value === 'string') {
        // Escape quotes and wrap in quotes
        return `"${value.replace(/"/g, '""')}"`;
      }
      if (Array.isArray(value)) {
        return `"${value.join(', ')}"`;
      }
      return `"${String(value)}"`;
    }).join(',')
  );

  // Combine header and rows
  const csv = [header, ...rows].join('\n');

  // Create blob and download
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `${filename}.csv`);
}

/**
 * Convert data to JSON format and trigger download
 */
export function exportToJSON<T>(data: T[], filename: string): void {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  downloadBlob(blob, `${filename}.json`);
}

/**
 * Generate a simple HTML report and trigger download as PDF-ready HTML
 */
export function exportToHTML<T extends Record<string, unknown>>(
  data: T[],
  filename: string,
  options: {
    title: string;
    subtitle?: string;
    columns?: { key: keyof T; label: string }[];
  }
): void {
  if (data.length === 0) {
    console.warn('No data to export');
    return;
  }

  const cols = options.columns || Object.keys(data[0]).map(key => ({
    key: key as keyof T,
    label: key.toString().replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
  }));

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${options.title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      padding: 40px;
      color: #1a1a1a;
      background: #fff;
    }
    .header { margin-bottom: 30px; }
    .header h1 { font-size: 24px; font-weight: 600; margin-bottom: 8px; }
    .header p { color: #666; font-size: 14px; }
    .meta { 
      display: flex; 
      gap: 20px; 
      margin-bottom: 20px; 
      padding: 15px;
      background: #f5f5f5;
      border-radius: 8px;
      font-size: 13px;
    }
    .meta span { color: #666; }
    .meta strong { color: #1a1a1a; }
    table { 
      width: 100%; 
      border-collapse: collapse; 
      font-size: 13px;
    }
    th { 
      text-align: left; 
      padding: 12px 16px;
      background: #f5f5f5;
      font-weight: 600;
      border-bottom: 2px solid #e0e0e0;
    }
    td { 
      padding: 12px 16px;
      border-bottom: 1px solid #e0e0e0;
    }
    tr:hover { background: #fafafa; }
    .footer {
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e0e0e0;
      font-size: 12px;
      color: #999;
    }
    @media print {
      body { padding: 20px; }
      .meta { background: #f9f9f9; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${options.title}</h1>
    ${options.subtitle ? `<p>${options.subtitle}</p>` : ''}
  </div>
  
  <div class="meta">
    <span>Total Records: <strong>${data.length}</strong></span>
    <span>Generated: <strong>${new Date().toLocaleString()}</strong></span>
  </div>
  
  <table>
    <thead>
      <tr>
        ${cols.map(col => `<th>${col.label}</th>`).join('')}
      </tr>
    </thead>
    <tbody>
      ${data.map(item => `
        <tr>
          ${cols.map(col => {
            const value = item[col.key];
            if (value === null || value === undefined) return '<td>-</td>';
            if (Array.isArray(value)) return `<td>${value.join(', ')}</td>`;
            return `<td>${String(value)}</td>`;
          }).join('')}
        </tr>
      `).join('')}
    </tbody>
  </table>
  
  <div class="footer">
    <p>Generated by Optimus SEO • ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>
  `.trim();

  const blob = new Blob([html], { type: 'text/html' });
  downloadBlob(blob, `${filename}.html`);
}

/**
 * Helper function to trigger file download
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export keywords data
 */
export interface KeywordExportData {
  keyword: string;
  volume: number;
  difficulty: number;
  cpc: number;
  position: number | null;
  intent: string;
  [key: string]: string | number | null;
}

export function exportKeywords(
  keywords: KeywordExportData[],
  format: 'csv' | 'json' | 'html',
  filename: string = 'keywords-export'
): void {
  const columns: { key: keyof KeywordExportData; label: string }[] = [
    { key: 'keyword', label: 'Keyword' },
    { key: 'volume', label: 'Search Volume' },
    { key: 'difficulty', label: 'Difficulty' },
    { key: 'cpc', label: 'CPC ($)' },
    { key: 'position', label: 'Position' },
    { key: 'intent', label: 'Intent' },
  ];

  switch (format) {
    case 'csv':
      exportToCSV(keywords, filename, columns);
      break;
    case 'json':
      exportToJSON(keywords, filename);
      break;
    case 'html':
      exportToHTML(keywords, filename, {
        title: 'Keyword Research Export',
        subtitle: `${keywords.length} keywords exported`,
        columns,
      });
      break;
  }
}

/**
 * Export site audit issues
 */
export interface AuditIssueExportData {
  title: string;
  severity: string;
  category: string;
  affectedPages: number;
  description: string;
  [key: string]: string | number;
}

export function exportAuditIssues(
  issues: AuditIssueExportData[],
  format: 'csv' | 'json' | 'html',
  filename: string = 'audit-issues-export'
): void {
  const columns: { key: keyof AuditIssueExportData; label: string }[] = [
    { key: 'title', label: 'Issue' },
    { key: 'severity', label: 'Severity' },
    { key: 'category', label: 'Category' },
    { key: 'affectedPages', label: 'Affected Pages' },
    { key: 'description', label: 'Description' },
  ];

  switch (format) {
    case 'csv':
      exportToCSV(issues, filename, columns);
      break;
    case 'json':
      exportToJSON(issues, filename);
      break;
    case 'html':
      exportToHTML(issues, filename, {
        title: 'Site Audit Issues Export',
        subtitle: `${issues.length} issues found`,
        columns,
      });
      break;
  }
}

/**
 * Export competitor data
 */
export interface CompetitorExportData {
  name: string;
  url: string;
  domainRating: number;
  organicTraffic: number;
  keywords: number;
  backlinks: number;
  marketShare: number;
  [key: string]: string | number;
}

export function exportCompetitors(
  competitors: CompetitorExportData[],
  format: 'csv' | 'json' | 'html',
  filename: string = 'competitors-export'
): void {
  const columns: { key: keyof CompetitorExportData; label: string }[] = [
    { key: 'name', label: 'Competitor' },
    { key: 'url', label: 'URL' },
    { key: 'domainRating', label: 'Domain Rating' },
    { key: 'organicTraffic', label: 'Organic Traffic' },
    { key: 'keywords', label: 'Keywords' },
    { key: 'backlinks', label: 'Backlinks' },
    { key: 'marketShare', label: 'Market Share (%)' },
  ];

  switch (format) {
    case 'csv':
      exportToCSV(competitors, filename, columns);
      break;
    case 'json':
      exportToJSON(competitors, filename);
      break;
    case 'html':
      exportToHTML(competitors, filename, {
        title: 'Competitor Analysis Export',
        subtitle: `${competitors.length} competitors analyzed`,
        columns,
      });
      break;
  }
}

/**
 * Export AI visibility mentions data
 */
export interface AIVisibilityExportData {
  platform: string;
  query: string;
  sentiment: string;
  position: number | null;
  snippet: string;
  date: string;
  [key: string]: string | number | null;
}

export function exportAIVisibility(
  mentions: AIVisibilityExportData[],
  format: 'csv' | 'json' | 'html',
  filename: string = 'ai-visibility-export'
): void {
  const columns: { key: keyof AIVisibilityExportData; label: string }[] = [
    { key: 'platform', label: 'Platform' },
    { key: 'query', label: 'Query' },
    { key: 'sentiment', label: 'Sentiment' },
    { key: 'position', label: 'Position' },
    { key: 'snippet', label: 'Snippet' },
    { key: 'date', label: 'Date' },
  ];

  switch (format) {
    case 'csv':
      exportToCSV(mentions, filename, columns);
      break;
    case 'json':
      exportToJSON(mentions, filename);
      break;
    case 'html':
      exportToHTML(mentions, filename, {
        title: 'AI Visibility Export',
        subtitle: `${mentions.length} LLM mentions analyzed`,
        columns,
      });
      break;
  }
}
